name: learning_state_management
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.5
  flutter_modular: ^4.5.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  #BLOC
  flutter_bloc: ^8.0.1
  # MOBX
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  #MOBX
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.4

flutter:
  uses-material-design: true
